DROP TABLE IF EXISTS log_public CASCADE;
DROP TABLE IF EXISTS gallery_images CASCADE;
DROP TABLE IF EXISTS gallery_tags CASCADE;
DROP TABLE IF EXISTS galleries CASCADE;
DROP TABLE IF EXISTS news_tags CASCADE;
DROP TABLE IF EXISTS news CASCADE;
DROP TABLE IF EXISTS search_index CASCADE;
DROP TABLE IF EXISTS site_lang CASCADE;
DROP TABLE IF EXISTS site_domain CASCADE;
DROP TABLE IF EXISTS user_site CASCADE;
DROP TABLE IF EXISTS user_lang CASCADE;
DROP TABLE IF EXISTS redirects CASCADE;
DROP TABLE IF EXISTS sites CASCADE;
DROP TABLE IF EXISTS tree_data CASCADE;
DROP TABLE IF EXISTS tree_data_pub CASCADE;
DROP TABLE IF EXISTS tree_struct CASCADE;
DROP TABLE IF EXISTS languages CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS menus CASCADE;
DROP TABLE IF EXISTS templates CASCADE;

DELETE FROM `group_permissions` WHERE perm = 'pages';
DELETE FROM `group_permissions` WHERE perm = 'languages';
DELETE FROM `group_permissions` WHERE perm = 'news';
DELETE FROM `group_permissions` WHERE perm = 'news/publish';
DELETE FROM `group_permissions` WHERE perm = 'news/publish_own';
DELETE FROM `group_permissions` WHERE perm = 'galleries';
DELETE FROM `group_permissions` WHERE perm = 'galleries/publish';
DELETE FROM `group_permissions` WHERE perm = 'galleries/publish_own';
DELETE FROM `group_permissions` WHERE perm = 'pages/permissions';
DELETE FROM `group_permissions` WHERE perm = 'pages/publish';
DELETE FROM `group_permissions` WHERE perm = 'pages/structure';
DELETE FROM `group_permissions` WHERE perm = 'pages/administrative';
DELETE FROM `group_permissions` WHERE perm = 'redirects';
DELETE FROM `group_permissions` WHERE perm = 'sites';
DELETE FROM `group_permissions` WHERE perm = 'users/languages';
DELETE FROM `group_permissions` WHERE perm = 'menus';
DELETE FROM `group_permissions` WHERE perm = 'templates';
DELETE FROM `group_permissions` WHERE perm = 'ptranslation';

DELETE FROM `permissions` WHERE perm = 'pages';
DELETE FROM `permissions` WHERE perm = 'languages';
DELETE FROM `permissions` WHERE perm = 'news';
DELETE FROM `permissions` WHERE perm = 'news/publish';
DELETE FROM `permissions` WHERE perm = 'news/publish_own';
DELETE FROM `permissions` WHERE perm = 'galleries';
DELETE FROM `permissions` WHERE perm = 'galleries/publish';
DELETE FROM `permissions` WHERE perm = 'galleries/publish_own';
DELETE FROM `permissions` WHERE perm = 'pages/permissions';
DELETE FROM `permissions` WHERE perm = 'pages/publish';
DELETE FROM `permissions` WHERE perm = 'pages/structure';
DELETE FROM `permissions` WHERE perm = 'pages/administrative';
DELETE FROM `permissions` WHERE perm = 'redirects';
DELETE FROM `permissions` WHERE perm = 'sites';
DELETE FROM `permissions` WHERE perm = 'users/languages';
DELETE FROM `permissions` WHERE perm = 'menus';
DELETE FROM `permissions` WHERE perm = 'templates';
DELETE FROM `permissions` WHERE perm = 'ptranslation';

DELETE FROM modules WHERE name = 'pages';
DELETE FROM modules WHERE name = 'news';
DELETE FROM modules WHERE name = 'galleries';
DELETE FROM modules WHERE name = 'redirects';
DELETE FROM modules WHERE name = 'languages';
DELETE FROM modules WHERE name = 'sites';
DELETE FROM modules WHERE name = 'menus';
DELETE FROM modules WHERE name = 'templates';
DELETE FROM modules WHERE name = 'ptranslation';
