volumes:
    minio:

services:
    apppub:
        environment:
            STORAGE_UPLOADS: "S3"
            S3_URL: "http://storage:9000"
            S3_ACCESS: "minioadmin"
            S3_SECRET: "minioadmin"
            S3_BUCKET: "testbucket"
        depends_on:
            - storage
