ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

CREATE TABLE migrations (
  migration number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  package varchar2(255) NOT NULL,
  installed timestamp DEFAULT SYSTIMESTAMP NOT NULL ,
  removed timestamp DEFAULT NULL,
  CONSTRAINT PK_MIGRATIONS PRIMARY KEY (migration)
);

CREATE TABLE config (
  k varchar2(255) NOT NULL,
  v varchar2(2000) DEFAULT '',
  PRIMARY KEY (k)
);
