ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

CREATE TABLE authentication (
  authentication number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  authenticator varchar2(128) NOT NULL,
  settings clob,
  position number NOT NULL,
  disabled number DEFAULT 0 NOT NULL,
  conditions varchar2(2000) DEFAULT '',
  CONSTRAINT PK_AUTHENTICATION PRIMARY KEY (authentication)
);


CREATE TABLE uploads (
  id number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  name clob DEFAULT '',
  location clob DEFAULT '',
  bytesize number DEFAULT 0 NOT NULL ,
  uploaded timestamp DEFAULT SYSTIMESTAMP NOT NULL ,
  hash varchar2(32) DEFAULT '' ,
  data clob DEFAULT '',
  settings clob DEFAULT '',
  CONSTRAINT PK_UPLOADS PRIMARY KEY (id)
);

CREATE TABLE users (
  usr number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  name varchar2(80) DEFAULT '' ,
  mail varchar2(255) DEFAULT '' ,
  tfa number DEFAULT 0 NOT NULL ,
  disabled number DEFAULT 0  NOT NULL ,
  avatar number  DEFAULT NULL,
  avatar_data clob DEFAULT '',
  data clob DEFAULT '',
  push clob DEFAULT '',
  sessions clob DEFAULT '',
  CONSTRAINT PK_USERS PRIMARY KEY (usr),
  CONSTRAINT FK_USER_AVATAR FOREIGN KEY (avatar) REFERENCES uploads (id)
);

CREATE TABLE permissions (
  perm varchar2(255)  NOT NULL ,
  created timestamp NOT NULL ,
  CONSTRAINT PK_PERMISSIONS PRIMARY KEY (perm)
);

CREATE TABLE grps (
  grp number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  name varchar2(255) NOT NULL ,
  created timestamp NOT NULL ,
  CONSTRAINT PK_GRPS PRIMARY KEY (grp)
);


-- Dumping structure for table webadmin.group_permissions
CREATE TABLE group_permissions (
  grp number  NOT NULL ,
  perm varchar2(255)  NOT NULL ,
  created timestamp NOT NULL ,
  CONSTRAINT PK_GROUPPERMS PRIMARY KEY (grp,perm),
  CONSTRAINT FK_GROUPPERMS_GRP FOREIGN KEY (grp) REFERENCES grps (grp) ON DELETE CASCADE ,
  CONSTRAINT FK_GROUPPERMS_PERMS FOREIGN KEY (perm) REFERENCES permissions (perm) ON DELETE CASCADE 
);

CREATE TABLE organization (
  org number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  lft number  NOT NULL ,
  rgt number  NOT NULL ,
  lvl number  NOT NULL ,
  pid number  DEFAULT NULL ,
  pos number  NOT NULL ,
  title varchar2(50) DEFAULT '' ,
  properties clob DEFAULT '' ,
  CONSTRAINT PK_ORGANIZATION PRIMARY KEY (org),
  CONSTRAINT FK_ORGANIZATION_PARENT FOREIGN KEY (pid) REFERENCES organization (org) ON DELETE CASCADE 
);

CREATE TABLE log (
  id number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  created timestamp DEFAULT SYSTIMESTAMP NOT NULL ,
  lvl varchar2(20) DEFAULT 'error' NOT NULL CHECK(lvl IN ('emergency','alert','critical','error','warning','notice','info','debug')),
  message varchar2(255) DEFAULT '' ,
  context clob DEFAULT '',
  request clob DEFAULT '',
  response clob DEFAULT '',
  ip varchar2(45) DEFAULT '' ,
  usr number  DEFAULT NULL ,
  usr_name varchar2(80) DEFAULT NULL ,
  CONSTRAINT PK_LOG PRIMARY KEY (id),
  CONSTRAINT FK_LOG_USER FOREIGN KEY (usr) REFERENCES users (usr)
);

CREATE TABLE mails (
  mail number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  recipient varchar2(1000) NOT NULL,
  subject varchar2(2000)  DEFAULT '',
  content clob DEFAULT '',
  priority number DEFAULT 0,
  added timestamp NOT NULL ,
  started timestamp DEFAULT NULL,
  finished timestamp DEFAULT NULL,
  result varchar2(255) DEFAULT '',
  CONSTRAINT PK_MAILS PRIMARY KEY (mail)
);

CREATE TABLE user_groups (
  usr number  NOT NULL ,
  grp number  NOT NULL ,
  main number DEFAULT 0 NOT NULL ,
  created timestamp NOT NULL ,
  CONSTRAINT PK_USERGROUPS PRIMARY KEY (usr,grp),
  CONSTRAINT FK_USERGROUPS_GROUPS FOREIGN KEY (grp) REFERENCES grps (grp) ON DELETE CASCADE ,
  CONSTRAINT FK_USERGROUPS_USERS FOREIGN KEY (usr) REFERENCES users (usr) ON DELETE CASCADE 
);

CREATE TABLE user_groups_provisional (
  usr number  NOT NULL ,
  grp number  NOT NULL ,
  created timestamp NOT NULL ,
  CONSTRAINT PK_USERGROUPSP PRIMARY KEY (usr,grp),
  CONSTRAINT FK_USERGROUPSP_GROUPS FOREIGN KEY (grp) REFERENCES grps (grp) ON DELETE CASCADE ,
  CONSTRAINT FK_USERGROUPSP_USERS FOREIGN KEY (usr) REFERENCES users (usr) ON DELETE CASCADE 
);


-- Data exporting was unselected.
-- Dumping structure for table webadmin.user_organizations
CREATE TABLE user_organizations (
  usr number  NOT NULL,
  org number  NOT NULL,
  CONSTRAINT PK_USERORG PRIMARY KEY (usr,org),
  CONSTRAINT FK_USERORG_ORG FOREIGN KEY (org) REFERENCES organization (org) ON DELETE CASCADE ,
  CONSTRAINT FK_USERORG_USER FOREIGN KEY (usr) REFERENCES users (usr) ON DELETE CASCADE 
);

-- Data exporting was unselected.
-- Dumping structure for table webadmin.user_providers
CREATE TABLE user_providers (
  usrprov number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  provider varchar2(80) NOT NULL ,
  id varchar2(500) NOT NULL ,
  usr number  NOT NULL ,
  name varchar2(500) DEFAULT '' ,
  data varchar2(4000) DEFAULT NULL ,
  created timestamp DEFAULT SYSTIMESTAMP NOT NULL ,
  used timestamp DEFAULT NULL ,
  disabled number DEFAULT 0  NOT NULL ,
  details clob DEFAULT '',
  CONSTRAINT PK_USERPROVIDERS PRIMARY KEY (usrprov),
  CONSTRAINT FK_USERPROVIDERS_USERS FOREIGN KEY (usr) REFERENCES users (usr) ON DELETE CASCADE 
);

CREATE TABLE modules (
  name varchar2(255),
  slug varchar2(255),
  loaded number default 0,
  classname varchar2(255),
  pos number default 0,
  settings clob DEFAULT '',
  CONSTRAINT PK_MODULES PRIMARY KEY (name)
);

CREATE TABLE user_pending (
  usrpend number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  provider varchar2(80) NOT NULL ,
  id varchar2(500) NOT NULL ,
  name varchar2(500) DEFAULT '' ,
  mail varchar2(500) DEFAULT '' ,
  created timestamp DEFAULT SYSTIMESTAMP NOT NULL ,
  details clob DEFAULT '',
  CONSTRAINT PK_USERPENDING PRIMARY KEY (usrpend)
);

-- Data exporting was unselected.
-- Dumping structure for table webadmin.versions
CREATE TABLE versions (
  tbl varchar2(255) NOT NULL ,
  id varchar2(255) NOT NULL ,
  created timestamp DEFAULT SYSTIMESTAMP NOT NULL ,
  entity clob DEFAULT '',
  reason varchar2(50) NOT NULL ,
  usr number DEFAULT 0  NOT NULL ,
  usr_name varchar2(80) NOT NULL 
);

CREATE TABLE log_system (
  id number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  created timestamp DEFAULT SYSTIMESTAMP NOT NULL,
  lvl varchar2(20) NOT NULL,
  message varchar2(255) DEFAULT '',
  context clob DEFAULT '',
  module varchar2(100) DEFAULT NULL,
  module_id varchar2(100) DEFAULT NULL,
  usr int DEFAULT NULL,
  CONSTRAINT PK_SYSLOG PRIMARY KEY (id),
  CONSTRAINT FK_SYSLOG_USER FOREIGN KEY (usr) REFERENCES users (usr) ON DELETE SET NULL
);
