CREATE TABLE collections (
  collection number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  name varchar2(255) NOT NULL,
  owner number NOT NULL,
  rw number DEFAULT 0 NOT NULL,
  PRIMARY KEY (collection),
  CONSTRAINT FK_COLLECTION_USER FOREIGN KEY (owner) REFERENCES users (usr)
);

CREATE TABLE collection_groups (
  collection number NOT NULL,
  grp number NOT NULL,
  rw number DEFAULT 0 NOT NULL,
  PRIMARY KEY (collection,grp),
  CONSTRAINT FK_COLLGROUPS_GRP FOREIGN KEY (grp) REFERENCES grps (grp),
  CONSTRAINT FK_COLLGROUPS_COLL FOREIGN KEY (collection) REFERENCES collections (collection)
);

CREATE TABLE upload_collections (
  upload number NOT NULL,
  collection number NOT NULL,
  PRIMARY KEY (upload,collection),
  CONSTRAINT FK_UPLOADCOLL_COLL FOREIGN KEY (collection) REFERENCES collections (collection),
  CONSTRAINT FK_UPLOADCOLL_FILE FOREIGN KEY (upload) REFERENCES uploads (id)
);

CREATE TABLE upload_user (
  upload number NOT NULL,
  usr number NOT NULL,
  PRIMARY KEY (upload,usr),
  CONSTRAINT FK_UPLOADUSR_USR FOREIGN KEY (usr) REFERENCES users (usr),
  CONSTRAINT FK_UPLOADUSR_UPL FOREIGN KEY (upload) REFERENCES uploads (id)
);
