CREATE TABLE uploads_versions (
  id number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  upload number NOT NULL ,
  version clob DEFAULT '',
  name clob DEFAULT '',
  location clob DEFAULT '',
  bytesize number DEFAULT 0 NOT NULL ,
  uploaded timestamp DEFAULT SYSTIMESTAMP NOT NULL ,
  hash varchar2(32) DEFAULT '' ,
  data clob DEFAULT '',
  settings clob DEFAULT '',
  CONSTRAINT PK_UVERS PRIMARY KEY (id),
  CONSTRAINT FK_UVERS_UPLOAD FOREIGN KEY (upload) REFERENCES uploads (id)
);
