ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

CREATE TABLE notifications (
  notification number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  thread number  DEFAULT NULL,
  sender number  DEFAULT NULL,
  title varchar2(250) DEFAULT '' ,
  body varchar2(2000) DEFAULT '' ,
  link varchar2(500) DEFAULT '' ,
  sent timestamp NOT NULL,
  reply number DEFAULT 0  NOT NULL,
  CONSTRAINT PK_NOTIFICATIONS PRIMARY KEY (notification),
  CONSTRAINT FK_NOTIFICATION_SENDER FOREIGN KEY (sender) REFERENCES users (usr),
  CONSTRAINT FK_NOTIFICATION_THREAD FOREIGN KEY (thread) REFERENCES notifications (notification)
);

CREATE TABLE notification_files (
  notification number NOT NULL,
  upload number NOT NULL,
  pos number  NOT NULL,
  PRIMARY KEY (notification,upload),
  CONSTRAINT FK_NOTIFFILES_NOTIF FOREIGN KEY (notification) REFERENCES notifications (notification),
  CONSTRAINT FK_NOTIFFILES_FILE FOREIGN KEY (upload) REFERENCES uploads (id)
);

CREATE TABLE notification_recipients (
  notification number  NOT NULL,
  recipient number  NOT NULL,
  opened timestamp DEFAULT NULL,
  mailed timestamp DEFAULT NULL,
  CONSTRAINT PK_NOTIFICATION_RECIPIENTS PRIMARY KEY (notification,recipient),
  CONSTRAINT FK_NOTIFICATION_RECIPIENT FOREIGN KEY (recipient) REFERENCES users (usr),
  CONSTRAINT FK_RECIPIENT_NOTIFICATION FOREIGN KEY (notification) REFERENCES notifications (notification)
);
