DROP TABLE IF EXISTS gallery_images ;
DROP TABLE IF EXISTS gallery_tags ;
DROP TABLE IF EXISTS galleries ;
DROP TABLE IF EXISTS user_site ;
DROP TABLE IF EXISTS user_lang ;
DROP TABLE IF EXISTS tree_data ;
DROP TABLE IF EXISTS tree_data_pub ;
DROP TABLE IF EXISTS site_lang ;
DROP TABLE IF EXISTS site_domain ;
DROP TABLE IF EXISTS search_index ;
DROP TABLE IF EXISTS redirects ;
DROP TABLE IF EXISTS news_tags ;
DROP TABLE IF EXISTS news ;
DROP TABLE IF EXISTS languages ;
DROP TABLE IF EXISTS tags ;
DROP TABLE IF EXISTS sites ;
DROP TABLE IF EXISTS tree_struct ;
DROP TABLE IF EXISTS log_public ;
DROP TABLE IF EXISTS menus ;
DROP TABLE IF EXISTS templates ;

DELETE FROM group_permissions WHERE perm = 'pages';
DELETE FROM group_permissions WHERE perm = 'languages';
DELETE FROM group_permissions WHERE perm = 'news';
DELETE FROM group_permissions WHERE perm = 'news/publish';
DELETE FROM group_permissions WHERE perm = 'news/publish_own';
DELETE FROM group_permissions WHERE perm = 'galleries';
DELETE FROM group_permissions WHERE perm = 'galleries/publish';
DELETE FROM group_permissions WHERE perm = 'galleries/publish_own';
DELETE FROM group_permissions WHERE perm = 'pages/permissions';
DELETE FROM group_permissions WHERE perm = 'pages/publish';
DELETE FROM group_permissions WHERE perm = 'pages/structure';
DELETE FROM group_permissions WHERE perm = 'pages/administrative';
DELETE FROM group_permissions WHERE perm = 'redirects';
DELETE FROM group_permissions WHERE perm = 'sites';
DELETE FROM group_permissions WHERE perm = 'users/languages';
DELETE FROM group_permissions WHERE perm = 'menus';
DELETE FROM group_permissions WHERE perm = 'templates';
DELETE FROM group_permissions WHERE perm = 'ptranslation';

DELETE FROM permissions WHERE perm = 'pages';
DELETE FROM permissions WHERE perm = 'languages';
DELETE FROM permissions WHERE perm = 'news';
DELETE FROM permissions WHERE perm = 'news/publish';
DELETE FROM permissions WHERE perm = 'news/publish_own';
DELETE FROM permissions WHERE perm = 'galleries';
DELETE FROM permissions WHERE perm = 'galleries/publish';
DELETE FROM permissions WHERE perm = 'galleries/publish_own';
DELETE FROM permissions WHERE perm = 'pages/permissions';
DELETE FROM permissions WHERE perm = 'pages/publish';
DELETE FROM permissions WHERE perm = 'pages/structure';
DELETE FROM permissions WHERE perm = 'pages/administrative';
DELETE FROM permissions WHERE perm = 'redirects';
DELETE FROM permissions WHERE perm = 'sites';
DELETE FROM permissions WHERE perm = 'users/languages';
DELETE FROM permissions WHERE perm = 'menus';
DELETE FROM permissions WHERE perm = 'templates';
DELETE FROM permissions WHERE perm = 'ptranslation';

DELETE FROM modules WHERE name = 'pages';
DELETE FROM modules WHERE name = 'news';
DELETE FROM modules WHERE name = 'galleries';
DELETE FROM modules WHERE name = 'redirects';
DELETE FROM modules WHERE name = 'languages';
DELETE FROM modules WHERE name = 'sites';
DELETE FROM modules WHERE name = 'menus';
DELETE FROM modules WHERE name = 'templates';
DELETE FROM modules WHERE name = 'ptranslation';
