ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

CREATE TABLE tree_struct (
  id number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  lft number  NOT NULL ,
  rgt number  NOT NULL ,
  lvl number  NOT NULL ,
  pid number  DEFAULT NULL ,
  pos number  NOT NULL ,
  CONSTRAINT PK_TREESTRUCT PRIMARY KEY (id),
  CONSTRAINT FK_TREENODE_PARENT FOREIGN KEY (pid) REFERENCES tree_struct (id) ON DELETE CASCADE 
);

CREATE TABLE sites (
  site number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  name varchar2(200)  NOT NULL ,
  domains varchar2(2000) DEFAULT '',
  tree number  DEFAULT NULL ,
  disabled number DEFAULT 0  NOT NULL,
  dflt number DEFAULT 0  NOT NULL,
  CONSTRAINT PK_SITES PRIMARY KEY (site),
  CONSTRAINT FK_SITES_TREE FOREIGN KEY (tree) REFERENCES tree_struct (id)
);

CREATE TABLE languages (
  lang number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  code char(2) NOT NULL ,
  name varchar2(200) NOT NULL ,
  local varchar2(200) NOT NULL ,
  CONSTRAINT PK_LANGUAGES PRIMARY KEY (lang),
  CONSTRAINT code UNIQUE (code)
);

CREATE TABLE tags (
  tag number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  lang number  NOT NULL,
  name varchar2(100) NOT NULL,
  CONSTRAINT PK_TAGS PRIMARY KEY (tag),
  CONSTRAINT FK_TAGS_LANGUAGE FOREIGN KEY (lang) REFERENCES languages (lang)
);

CREATE TABLE log_public (
  id number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  created timestamp DEFAULT SYSTIMESTAMP NOT NULL ,
  lvl varchar2(20) DEFAULT 'error' NOT NULL CHECK(lvl IN ('emergency','alert','critical','error','warning','notice','info','debug')),
  message varchar2(255) DEFAULT '' ,
  context clob DEFAULT '',
  request clob DEFAULT '',
  response clob DEFAULT '',
  ip varchar2(45) DEFAULT '' ,
  ua varchar2(512) DEFAULT '' ,
  CONSTRAINT PK_LOGPUBLIC PRIMARY KEY (id)
);

CREATE TABLE news (
  news number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  lang number  NOT NULL,
  fordate date NOT NULL,
  title varchar2(1000) DEFAULT '',
  image number DEFAULT NULL,
  content clob DEFAULT '',
  hidden number DEFAULT 0  NOT NULL,
  visible_beg timestamp NOT NULL,
  visible_end timestamp DEFAULT NULL,
  site number  DEFAULT NULL,
  CONSTRAINT PK_NEWS PRIMARY KEY (news),
  CONSTRAINT FK_NEWS_LANGUAGE FOREIGN KEY (lang) REFERENCES languages (lang),
  CONSTRAINT FK_NEWS_IMAGE FOREIGN KEY (image) REFERENCES uploads (id),
  CONSTRAINT FK_NEWS_SITE FOREIGN KEY (site) REFERENCES sites (site) ON DELETE CASCADE 
);

CREATE TABLE news_tags (
  news number  NOT NULL,
  tag number  NOT NULL,
  CONSTRAINT PK_NEWSTAGS PRIMARY KEY (news,tag),
  CONSTRAINT FK_NEWSTAGS_NEWS FOREIGN KEY (news) REFERENCES news (news),
  CONSTRAINT FK_NEWSTAGS_TAG FOREIGN KEY (tag) REFERENCES tags (tag)
);

CREATE TABLE galleries (
  gallery number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  lang number  NOT NULL,
  fordate date NOT NULL,
  title varchar2(1000) DEFAULT '',
  content clob DEFAULT '',
  hidden number DEFAULT 0  NOT NULL,
  visible_beg timestamp NOT NULL,
  visible_end timestamp DEFAULT NULL,
  site number  DEFAULT NULL,
  CONSTRAINT PK_GALLERIES PRIMARY KEY (gallery),
  CONSTRAINT FK_GALLERIES_LANGUAGE FOREIGN KEY (lang) REFERENCES languages (lang),
  CONSTRAINT FK_GALLERIES_SITE FOREIGN KEY (site) REFERENCES sites (site) ON DELETE CASCADE 
);

CREATE TABLE gallery_images (
  gallery number  NOT NULL,
  upload number  NOT NULL,
  pos number  NOT NULL,
  CONSTRAINT PK_GALLERYIMAGES PRIMARY KEY (gallery,upload),
  CONSTRAINT FK_GALLERYIMAGES_GALLERY FOREIGN KEY (gallery) REFERENCES galleries (gallery),
  CONSTRAINT FK_GALLERYIMAGES_IMAGE FOREIGN KEY (upload) REFERENCES uploads (id)
);

CREATE TABLE gallery_tags (
  gallery number  NOT NULL,
  tag number  NOT NULL,
  CONSTRAINT PK_GALLERYTAGS PRIMARY KEY (gallery,tag),
  CONSTRAINT FK_GALLERYTAGS_GALLERY FOREIGN KEY (gallery) REFERENCES galleries (gallery),
  CONSTRAINT FK_GALLERYTAGS_TAG FOREIGN KEY (tag) REFERENCES tags (tag)
);

CREATE TABLE redirects (
  redirect number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  url_from varchar2(2000) DEFAULT ''  ,
  url_to varchar2(2000) DEFAULT '' ,
  rtype varchar2(20) DEFAULT 'none' ,
  site number DEFAULT NULL,
  CONSTRAINT PK_REDIRECTS PRIMARY KEY (redirect),
  CONSTRAINT FK_REDIRECT_SITE FOREIGN KEY (site) REFERENCES sites (site) ON DELETE CASCADE 
);

CREATE TABLE search_index (
  si varchar2(40) NOT NULL,
  url varchar2(2000) NOT NULL,
  title varchar2(2000) DEFAULT '' ,
  data clob DEFAULT '',
  meta clob DEFAULT '',
  indexed timestamp NOT NULL,
  remove number DEFAULT 0 NOT NULL,
  site number  DEFAULT NULL,
  lang number  DEFAULT NULL,
  CONSTRAINT PK_SEARCHINDEX PRIMARY KEY (si),
  CONSTRAINT FK_SEARCH_SITE FOREIGN KEY (site) REFERENCES sites (site) ON DELETE CASCADE,
  CONSTRAINT FK_SEARCH_LANG FOREIGN KEY (lang) REFERENCES languages (lang) ON DELETE CASCADE 
) ;

CREATE TABLE site_domain (
  site number  NOT NULL,
  domain varchar2(500) NOT NULL,
  CONSTRAINT PK_SITEDOMAIN PRIMARY KEY (site,domain),
  CONSTRAINT FK_SITEDOMAIN_SITE FOREIGN KEY (site) REFERENCES sites (site)
);

CREATE TABLE site_lang (
  site number  NOT NULL,
  lang number  NOT NULL,
  CONSTRAINT PK_SITELANG PRIMARY KEY (site,lang),
  CONSTRAINT FK_SITELANG_LANG FOREIGN KEY (lang) REFERENCES languages (lang) ON DELETE CASCADE ,
  CONSTRAINT FK_SITELANG_SITE FOREIGN KEY (site) REFERENCES sites (site) ON DELETE CASCADE 
);

CREATE TABLE templates (
  template number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  name varchar2(255) DEFAULT '',
  base varchar2(255) DEFAULT '',
  is_default number DEFAULT 0 NOT NULL ,
  child_default number DEFAULT NULL,
  widgets clob DEFAULT '',
  zones clob DEFAULT '',
  CONSTRAINT PK_TEMPLATES PRIMARY KEY (template),
  CONSTRAINT FK_CHILD_TEMPLATE FOREIGN KEY (child_default) REFERENCES templates (template)
) ;

CREATE TABLE menus (
  menu number GENERATED BY DEFAULT ON NULL as IDENTITY(START with 1 INCREMENT by 1),
  name varchar2(255) DEFAULT '',
  slug varchar2(255) DEFAULT '',
  site number  NOT NULL,
  lang number  NOT NULL,
  is_default number DEFAULT 0 NOT NULL ,
  items clob DEFAULT '',
  CONSTRAINT PK_MENUS PRIMARY KEY (menu)
) ;

CREATE TABLE tree_data (
  id number  NOT NULL,
  lang number  NOT NULL ,
  version number  NOT NULL ,
  from_version number DEFAULT NULL,
  created timestamp DEFAULT SYSTIMESTAMP NOT NULL ,
  usr number DEFAULT 0  NOT NULL ,
  title varchar2(255) DEFAULT '' ,
  hidden number DEFAULT 0  NOT NULL ,
  url varchar2(255) DEFAULT '',
  redirect varchar2(1024) DEFAULT '' ,
  settings clob DEFAULT '',
  content clob DEFAULT '',
  permissions clob DEFAULT '',
  template number NOT NULL ,
  menu number DEFAULT NULL ,
  published number DEFAULT 0  NOT NULL ,
  CONSTRAINT PK_TREEDATA PRIMARY KEY (id,lang,version),
  CONSTRAINT FK_TREE_LANG FOREIGN KEY (lang) REFERENCES languages (lang),
  CONSTRAINT FK_TREE_STRUCT FOREIGN KEY (id) REFERENCES tree_struct (id),
  CONSTRAINT FK_TREE_USR FOREIGN KEY (usr) REFERENCES users (usr),
  CONSTRAINT FK_TREE_TEMPLATE FOREIGN KEY (template) REFERENCES templates (template),
  CONSTRAINT FK_TREE_MENU FOREIGN KEY (menu) REFERENCES menus (menu)
);

CREATE TABLE tree_data_pub (
  id number  NOT NULL,
  lang number  NOT NULL ,
  version number  NOT NULL ,
  from_version number DEFAULT NULL,
  created timestamp DEFAULT SYSTIMESTAMP NOT NULL ,
  usr number DEFAULT 0  NOT NULL ,
  title varchar2(255) DEFAULT '' ,
  hidden number DEFAULT 0  NOT NULL ,
  url varchar2(255) DEFAULT '',
  redirect varchar2(1024) DEFAULT '' ,
  settings clob DEFAULT '',
  content clob DEFAULT '',
  permissions clob DEFAULT '',
  template number NOT NULL ,
  menu number DEFAULT NULL ,
  published number DEFAULT 0  NOT NULL ,
  CONSTRAINT PK_TREEDATAPUB PRIMARY KEY (id,lang),
  CONSTRAINT FK_TREEPUB_LANG FOREIGN KEY (lang) REFERENCES languages (lang),
  CONSTRAINT FK_TREEPUB_STRUCT FOREIGN KEY (id) REFERENCES tree_struct (id),
  CONSTRAINT FK_TREEPUB_USR FOREIGN KEY (usr) REFERENCES users (usr),
  CONSTRAINT FK_TREEPUB_TEMPLATE FOREIGN KEY (template) REFERENCES templates (template),
  CONSTRAINT FK_TREEPUB_MENU FOREIGN KEY (menu) REFERENCES menus (menu)
);

-- Data exporting was unselected.
-- Dumping structure for table webadmin.user_lang
CREATE TABLE user_lang (
  usr number  NOT NULL,
  lang number  NOT NULL,
  CONSTRAINT PK_USERLANG PRIMARY KEY (usr,lang),
  CONSTRAINT FK_USERLANG_LANG FOREIGN KEY (lang) REFERENCES languages (lang) ON DELETE CASCADE ,
  CONSTRAINT FK_USERLANG_USER FOREIGN KEY (usr) REFERENCES users (usr) ON DELETE CASCADE 
);

-- Data exporting was unselected.
-- Dumping structure for table webadmin.user_site
CREATE TABLE user_site (
  usr number  NOT NULL,
  site number  NOT NULL,
  CONSTRAINT PK_USERSITE PRIMARY KEY (usr,site),
  CONSTRAINT FK_USERSITE_SITE FOREIGN KEY (site) REFERENCES sites (site) ON DELETE CASCADE ,
  CONSTRAINT FK_USERSITE_USER FOREIGN KEY (usr) REFERENCES users (usr) ON DELETE CASCADE 
);
