DROP TABLE gallery_images CASCADE CONSTRAINTS;
DROP TABLE gallery_tags CASCADE CONSTRAINTS;
DROP TABLE galleries CASCADE CONSTRAINTS;
DROP TABLE user_site CASCADE CONSTRAINTS;
DROP TABLE user_lang CASCADE CONSTRAINTS;
DROP TABLE tree_data CASCADE CONSTRAINTS;
DROP TABLE tree_data_pub CASCADE CONSTRAINTS;
DROP TABLE site_lang CASCADE CONSTRAINTS;
DROP TABLE site_domain CASCADE CONSTRAINTS;
DROP TABLE search_index CASCADE CONSTRAINTS;
DROP TABLE redirects CASCADE CONSTRAINTS;
DROP TABLE news_tags CASCADE CONSTRAINTS;
DROP TABLE news CASCADE CONSTRAINTS;
DROP TABLE languages CASCADE CONSTRAINTS;
DROP TABLE tags CASCADE CONSTRAINTS;
DROP TABLE sites CASCADE CONSTRAINTS;
DROP TABLE tree_struct CASCADE CONSTRAINTS;
DROP TABLE log_public CASCADE CONSTRAINTS;
DROP TABLE menus CASCADE CONSTRAINTS;
DROP TABLE templates CASCADE CONSTRAINTS;

DELETE FROM group_permissions WHERE perm = 'pages';
DELETE FROM group_permissions WHERE perm = 'languages';
DELETE FROM group_permissions WHERE perm = 'news';
DELETE FROM group_permissions WHERE perm = 'news/publish';
DELETE FROM group_permissions WHERE perm = 'news/publish_own';
DELETE FROM group_permissions WHERE perm = 'galleries';
DELETE FROM group_permissions WHERE perm = 'galleries/publish';
DELETE FROM group_permissions WHERE perm = 'galleries/publish_own';
DELETE FROM group_permissions WHERE perm = 'pages/permissions';
DELETE FROM group_permissions WHERE perm = 'pages/publish';
DELETE FROM group_permissions WHERE perm = 'pages/structure';
DELETE FROM group_permissions WHERE perm = 'pages/administrative';
DELETE FROM group_permissions WHERE perm = 'redirects';
DELETE FROM group_permissions WHERE perm = 'sites';
DELETE FROM group_permissions WHERE perm = 'users/languages';
DELETE FROM group_permissions WHERE perm = 'menus';
DELETE FROM group_permissions WHERE perm = 'templates';
DELETE FROM group_permissions WHERE perm = 'ptranslation';

DELETE FROM permissions WHERE perm = 'pages';
DELETE FROM permissions WHERE perm = 'languages';
DELETE FROM permissions WHERE perm = 'news';
DELETE FROM permissions WHERE perm = 'news/publish';
DELETE FROM permissions WHERE perm = 'news/publish_own';
DELETE FROM permissions WHERE perm = 'galleries';
DELETE FROM permissions WHERE perm = 'galleries/publish';
DELETE FROM permissions WHERE perm = 'galleries/publish_own';
DELETE FROM permissions WHERE perm = 'pages/permissions';
DELETE FROM permissions WHERE perm = 'pages/publish';
DELETE FROM permissions WHERE perm = 'pages/structure';
DELETE FROM permissions WHERE perm = 'pages/administrative';
DELETE FROM permissions WHERE perm = 'redirects';
DELETE FROM permissions WHERE perm = 'sites';
DELETE FROM permissions WHERE perm = 'users/languages';
DELETE FROM permissions WHERE perm = 'menus';
DELETE FROM permissions WHERE perm = 'templates';
DELETE FROM permissions WHERE perm = 'ptranslation';

DELETE FROM modules WHERE name = 'pages';
DELETE FROM modules WHERE name = 'news';
DELETE FROM modules WHERE name = 'galleries';
DELETE FROM modules WHERE name = 'redirects';
DELETE FROM modules WHERE name = 'languages';
DELETE FROM modules WHERE name = 'sites';
DELETE FROM modules WHERE name = 'menus';
DELETE FROM modules WHERE name = 'templates';
DELETE FROM modules WHERE name = 'ptranslation';
